version: '3'
services:
  arbo-db:
    build: ./db   
    image: arbo-db:1.0
    ports:
      - 3306:3306
    command: --max_allowed_packet=325058567
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}      
    networks:
      - db

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      # - VIRTUAL_HOST=grafana.loc
      # - GF_SERVER_ROOT_URL=http://grafana.loc
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=password
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=arbo-db:3306
      - GF_DATABASE_MAX_OPEN_CONN=30
      - GF_SESSION_PROVIDER=mysql
      - GF_SESSION_PROVIDER_CONFIG=grafana:password@tcp(arbo-db:3306)/grafana?allowNativePasswords=true
      # - GF_SERVER_ROUTER_LOGGING=true
      # - GF_LOG_CONSOLE_FORMAT=json
      # - GF_LOG_FILTERS=alerting.notifier:debug,alerting.notifier.slack:debug,auth:debug
      # - GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES=2
      - GF_INSTALL_PLUGINS=grafana-clock-panel,vonage-status-panel,flant-statusmap-panel,snuids-radar-panel,neocat-cal-heatmap-panel,briangann-gauge-panel
    networks:
      - db
    ports:
      - 3000
        
  # Arbo1 App
  ib-generate:
    build: ./ib-generate
    image: ib-generate:1.0
    depends_on:
      - arbo-db
    networks:
      - db
      - web

  tws:
    build: ./gateway
    ports:
      - "4003:4003"
      - "5901:5900"
    volumes:
      - ./gateway/ib/IBController.ini:/root/IBController/IBController.ini
      - ./gateway/ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=America/Chicago
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=1234 # CHANGEME
      - TWS_MAJOR_VRSN=974
      - IBC_INI=/root/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - JAVA_PATH=/opt/i4j_jres/1.8.0_152/bin # JRE is bundled starting with TWS 952 
      - TRADING_MODE=paper # either paper or live
      - TWSUSERID=vishal682 # IB account
      - TWSPASSWORD=VishalD123 # IB account password
      - FIXUSERID=
      - FIXPASSWORD=
      - APP=GATEWAY
    networks:
       - db


networks:
  db:
    driver: bridge
  web:
    driver: bridge
    
volumes:
  db-data:
  grafana-storage:
